# Generated by Django 2.2.17 on 2021-04-22 18:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import invoices.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summa', models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='Сумма оплаты')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата оплаты')),
                ('file', models.FileField(blank=True, null=True, upload_to=invoices.models.make_invoice_path, verbose_name='Файл квитанции')),
                ('registration_date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата регистрации')),
                ('payer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Плательщик')),
            ],
            options={
                'verbose_name_plural': 'Квитанции',
                'verbose_name': 'Квитанция',
                'ordering': ['payer'],
            },
        ),
    ]
