# Generated by Django 2.2.24 on 2023-09-18 15:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import pictures.models


class Migration(migrations.Migration):

    dependencies = [
        ('pictures', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='add_view_1',
            field=models.ImageField(blank=True, null=True, upload_to=pictures.models.make_picture_path, verbose_name='Дополнительный вид'),
        ),
        migrations.AddField(
            model_name='picture',
            name='add_view_2',
            field=models.ImageField(blank=True, null=True, upload_to=pictures.models.make_picture_path, verbose_name='Дополнительный вид'),
        ),
        migrations.AddField(
            model_name='picture',
            name='participation',
            field=models.CharField(choices=[('1', 'очное'), ('2', 'заочное')], default='1', max_length=1, verbose_name='Тип участия*'),
        ),
        migrations.AlterField(
            model_name='picture',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор работы*'),
        ),
        migrations.AlterField(
            model_name='picture',
            name='file',
            field=models.ImageField(blank=True, null=True, upload_to=pictures.models.make_picture_path, verbose_name='Изображение работы*'),
        ),
        migrations.AlterField(
            model_name='picture',
            name='name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Название работы*'),
        ),
        migrations.AlterField(
            model_name='picture',
            name='nomination',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nominations.ArtNomination', verbose_name='Номинация*'),
        ),
    ]
