# Generated by Django 2.2.24 on 2023-09-18 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pictures', '0002_auto_20230918_1809'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='add_views',
            field=models.BooleanField(default=True, verbose_name='Дополнительные ракурсы'),
        ),
    ]
