# Generated by Django 2.2.24 on 2023-09-18 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pictures', '0003_picture_add_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='add_views',
            field=models.BooleanField(default=False, verbose_name='Дополнительные ракурсы'),
        ),
    ]
