# Generated by Django 2.2.24 on 2023-09-18 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pictures', '0006_auto_20230918_2229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profileuser.CoProfile', verbose_name='Автор работы*'),
        ),
    ]
