# Generated by Django 2.2.24 on 2023-09-21 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pictures', '0007_auto_20230918_2230'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='ages',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=2, verbose_name='Возраст на момент написания работы*'),
        ),
        migrations.AddField(
            model_name='picture',
            name='summa',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=4, verbose_name='Год исполгения работы*'),
        ),
    ]
