# Generated by Django 2.2.24 on 2023-10-14 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pictures', '0010_auto_20230921_2305'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='place',
            field=models.DecimalField(blank=True, decimal_places=0, default=None, max_digits=1, null=True, verbose_name='Место'),
        ),
    ]
