# Generated by Django 2.2.24 on 2024-09-19 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pictures', '0011_picture_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='participation',
            field=models.CharField(choices=[('1', 'очное'), ('2', 'заочное')], default='2', max_length=1, verbose_name='Тип участия*'),
        ),
    ]
