# Generated by Django 2.2.17 on 2021-04-22 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nomination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='Техника исполнения')),
            ],
            options={
                'verbose_name_plural': 'Техники исполнения',
                'verbose_name': 'Техника исполнения',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SubNomination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='Направление')),
                ('nomination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nominations.Nomination', verbose_name='Техника исполнения')),
            ],
            options={
                'verbose_name_plural': 'Направления техники исполнения',
                'verbose_name': 'Направление техники исполнения',
                'ordering': ['name'],
            },
        ),
    ]
