# Generated by Django 2.2.24 on 2023-09-18 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArtNomination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='Номинация (ДПИ)')),
            ],
            options={
                'verbose_name': 'Номинация (ДПИ)',
                'verbose_name_plural': 'Номинации (ДПИ)',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='VocalNomination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='Номинация (Вокал)')),
            ],
            options={
                'verbose_name': 'Номинация (Вокал)',
                'verbose_name_plural': 'Номинации (Вокал)',
                'ordering': ['name'],
            },
        ),
    ]
