# Generated by Django 2.2.24 on 2021-09-26 15:29

import certificates.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('1', 'Диплом лауреата'), ('2', 'Диплом учасника'), ('3', 'Благодарственное письмо'), ('4', 'Сертификат')], default='4', max_length=1, verbose_name='Тип')),
                ('certificate_num', models.CharField(blank=True, max_length=30, verbose_name='Номер сертификата')),
                ('certificate_file', models.FileField(blank=True, null=True, upload_to=certificates.models.make_certificate_path, verbose_name='Сертификат')),
                ('registration_date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата создания')),
                ('contestant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Конкурсант')),
            ],
            options={
                'verbose_name': 'Сертификат',
                'verbose_name_plural': 'Сертификаты',
                'ordering': ['type', 'certificate_num'],
            },
        ),
    ]
