# Generated by Django 2.2.17 on 2021-04-22 18:35

import children.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teachers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(blank=True, max_length=50, verbose_name='Фамилия участника')),
                ('name', models.CharField(blank=True, max_length=30, verbose_name='Имя участника')),
                ('name2', models.CharField(blank=True, max_length=30, verbose_name='Отчество участника')),
                ('age', models.DecimalField(blank=True, decimal_places=0, default=None, max_digits=2, null=True, verbose_name='Возраст участника')),
                ('group', models.CharField(blank=True, choices=[('1', 'Студенты СПО'), ('2', 'Студенты ВПО'), ('3', 'ДШИ, ДХШ (13-14 лет)'), ('4', 'ДШИ, ДХШ (от 15 лет)')], default=None, max_length=1, null=True, verbose_name='Возрастная группа')),
                ('master_flag', models.BooleanField(default=False, verbose_name='Участие в конкурсе профессионального мастерства')),
                ('teacher_plus_flag', models.BooleanField(default=False, verbose_name='Другой преподаватель')),
                ('file_one', models.ImageField(blank=True, null=True, upload_to=children.models.make_picture_path, verbose_name='Изображение первого этапа')),
                ('file_two', models.ImageField(blank=True, null=True, upload_to=children.models.make_picture_path, verbose_name='Изображение второго этапа')),
                ('file_fin', models.ImageField(blank=True, null=True, upload_to=children.models.make_picture_path, verbose_name='Изображение законченной работы')),
                ('certificate_num', models.CharField(blank=True, max_length=30, verbose_name='Номер сертификата')),
                ('registration_date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата регистрации')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Преподаватель (Администратор)')),
                ('teacher_plus', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='teachers.Teacher', verbose_name='Преподаватель:')),
            ],
            options={
                'verbose_name_plural': 'Участники',
                'verbose_name': 'Участник',
                'ordering': ['surname', 'name', 'name2'],
            },
        ),
    ]
