# Generated by Django 2.2.17 on 2021-04-22 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('children', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='child',
            name='certificate_num',
        ),
    ]
