# Generated by Django 2.2.17 on 2021-04-22 18:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import teachers.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(blank=True, max_length=50, verbose_name='Фамилия преподавателя')),
                ('name', models.CharField(blank=True, max_length=30, verbose_name='Имя преподавателя')),
                ('name2', models.CharField(blank=True, max_length=30, verbose_name='Отчество преподавателя')),
                ('certificate_num', models.CharField(blank=True, max_length=30, verbose_name='Номер сертификата')),
                ('certificate_file', models.FileField(blank=True, null=True, upload_to=teachers.models.make_certificate_path, verbose_name='Сертификат')),
                ('registration_date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата регистрации')),
                ('host_accaunt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Администратор учреждения:')),
            ],
            options={
                'verbose_name_plural': 'Преподаватели',
                'verbose_name': 'Преподаватель',
                'ordering': ['surname', 'name', 'name2'],
            },
        ),
    ]
