# Generated by Django 2.2.24 on 2021-09-26 15:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pictures', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PictureMark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criterai_one', models.DecimalField(blank=True, decimal_places=0, default=None, max_digits=2, null=True, verbose_name='Соответствие выбранной теме')),
                ('criterai_two', models.DecimalField(blank=True, decimal_places=0, default=None, max_digits=2, null=True, verbose_name='Техническое воспроизведение')),
                ('criterai_three', models.DecimalField(blank=True, decimal_places=0, default=None, max_digits=2, null=True, verbose_name='Авторское новаторство')),
                ('criterai_four', models.DecimalField(blank=True, decimal_places=0, default=None, max_digits=2, null=True, verbose_name='Эстетика подачи работы')),
                ('criterai_five', models.DecimalField(blank=True, decimal_places=0, default=None, max_digits=2, null=True, verbose_name='Визуальное восприятие')),
                ('expert', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Член жюри')),
                ('work', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pictures.Picture', verbose_name='Работа')),
            ],
            options={
                'verbose_name': 'Оценка работы',
                'verbose_name_plural': 'Оценки работы',
                'ordering': ['work'],
            },
        ),
        migrations.CreateModel(
            name='MasterMark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criterai_one', models.DecimalField(blank=True, decimal_places=0, default=None, max_digits=2, null=True, verbose_name='Соответствие выбранной теме')),
                ('criterai_two', models.DecimalField(blank=True, decimal_places=0, default=None, max_digits=2, null=True, verbose_name='Техническое воспроизведение')),
                ('criterai_three', models.DecimalField(blank=True, decimal_places=0, default=None, max_digits=2, null=True, verbose_name='Авторское новаторство')),
                ('criterai_four', models.DecimalField(blank=True, decimal_places=0, default=None, max_digits=2, null=True, verbose_name='Эстетика подачи работы')),
                ('criterai_five', models.DecimalField(blank=True, decimal_places=0, default=None, max_digits=2, null=True, verbose_name='Визуальное восприятие')),
                ('expert', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Член жюри')),
            ],
            options={
                'verbose_name': 'Оценка проф.мастерства',
                'verbose_name_plural': 'Оценки проф.мастерства',
                'ordering': ['expert'],
            },
        ),
    ]
