# Generated by Django 2.2.24 on 2023-09-18 06:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pictures', '0001_initial'),
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PictureMark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criterai_one', models.DecimalField(blank=True, decimal_places=0, default=None, max_digits=2, null=True, verbose_name='Соответствие названию, полнота раскрытия')),
                ('criterai_two', models.DecimalField(blank=True, decimal_places=0, default=None, max_digits=2, null=True, verbose_name='Техническое воспроизведение')),
                ('criterai_three', models.DecimalField(blank=True, decimal_places=0, default=None, max_digits=2, null=True, verbose_name='Авторское новаторство')),
                ('criterai_four', models.DecimalField(blank=True, decimal_places=0, default=None, max_digits=2, null=True, verbose_name='Эстетика подачи работы')),
                ('criterai_five', models.DecimalField(blank=True, decimal_places=0, default=None, max_digits=2, null=True, verbose_name='Визуальное восприятие')),
                ('expert', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Член жюри')),
                ('work', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pictures.Picture', verbose_name='Работа')),
            ],
            options={
                'verbose_name': 'Оценка работы (ДПИ)',
                'verbose_name_plural': 'Оценки работы (ДПИ)',
                'ordering': ['work'],
            },
        ),
        migrations.CreateModel(
            name='MovieMark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criterai_one', models.DecimalField(blank=True, decimal_places=0, default=None, max_digits=2, null=True, verbose_name='Сложность и трактовка музыкальных произведений')),
                ('criterai_two', models.DecimalField(blank=True, decimal_places=0, default=None, max_digits=2, null=True, verbose_name='Интонационная выразительность')),
                ('criterai_three', models.DecimalField(blank=True, decimal_places=0, default=None, max_digits=2, null=True, verbose_name='Артистизм')),
                ('expert', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Член жюри')),
                ('work', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='movies.Movie', verbose_name='Работа')),
            ],
            options={
                'verbose_name': 'Оценка работы (Вокал)',
                'verbose_name_plural': 'Оценки работы (Вокал)',
                'ordering': ['work'],
            },
        ),
    ]
