# Generated by Django 2.2.24 on 2021-09-30 14:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movies', '0002_auto_20210927_0101'),
        ('marks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieMark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criterai_one', models.DecimalField(blank=True, decimal_places=0, default=None, max_digits=2, null=True, verbose_name='Сложность и трактовка музыкальных произведений')),
                ('criterai_two', models.DecimalField(blank=True, decimal_places=0, default=None, max_digits=2, null=True, verbose_name='Интонационная выразительность')),
                ('criterai_three', models.DecimalField(blank=True, decimal_places=0, default=None, max_digits=2, null=True, verbose_name='Артистизм')),
                ('expert', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Член жюри')),
                ('work', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='movies.Movie', verbose_name='Работа')),
            ],
            options={
                'ordering': ['work'],
                'verbose_name': 'Оценка работы (Вокал)',
                'verbose_name_plural': 'Оценки работы (Вокал)',
            },
        ),
        migrations.AlterModelOptions(
            name='picturemark',
            options={'ordering': ['work'], 'verbose_name': 'Оценка работы (ДПИ)', 'verbose_name_plural': 'Оценки работы (ДПИ)'},
        ),
        migrations.AlterField(
            model_name='picturemark',
            name='criterai_one',
            field=models.DecimalField(blank=True, decimal_places=0, default=None, max_digits=2, null=True, verbose_name='Соответствие названию, полнота раскрытия'),
        ),
        migrations.DeleteModel(
            name='MasterMark',
        ),
    ]
