# Generated by Django 2.2.24 on 2021-09-26 16:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nominations', '0002_auto_20210926_1831'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='Название произведения')),
                ('composer', models.CharField(blank=True, max_length=110, verbose_name='Автор музыки')),
                ('poet', models.CharField(blank=True, max_length=100, verbose_name='Автор слов')),
                ('descritpion', models.CharField(blank=True, max_length=250, verbose_name='Описание')),
                ('file', models.URLField(blank=True, max_length=250, null=True, verbose_name='Ссылка на файл в YouTube')),
                ('registration_date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата регистрации')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Исполнитель')),
                ('nomination', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nominations.VocalNomination', verbose_name='Номинация')),
            ],
            options={
                'ordering': ['nomination', 'name'],
                'verbose_name': 'Песня',
                'verbose_name_plural': 'Песни',
            },
        ),
    ]
