# Generated by Django 2.2.24 on 2021-09-26 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='youtube_flag',
            field=models.BooleanField(default=False, verbose_name='Признак YouTube'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='file',
            field=models.URLField(blank=True, max_length=250, null=True, verbose_name='Ссылка на файл'),
        ),
    ]
