# Generated by Django 2.2.24 on 2023-09-18 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movie',
            options={'ordering': ['nomination', 'name_1', 'name_2'], 'verbose_name': 'Песня', 'verbose_name_plural': 'Песни'},
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='composer',
            new_name='composer_1',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='descritpion',
            new_name='descritpion_1',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='file',
            new_name='file_1',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='poet',
            new_name='poet_1',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='youtube_flag',
            new_name='youtube_flag_1',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='name',
        ),
        migrations.AddField(
            model_name='movie',
            name='composer_2',
            field=models.CharField(blank=True, max_length=110, verbose_name='Автор музыки'),
        ),
        migrations.AddField(
            model_name='movie',
            name='descritpion_2',
            field=models.CharField(blank=True, max_length=250, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='movie',
            name='file_2',
            field=models.URLField(blank=True, max_length=250, null=True, verbose_name='Ссылка на файл'),
        ),
        migrations.AddField(
            model_name='movie',
            name='name_1',
            field=models.CharField(blank=True, max_length=100, verbose_name='Название произведения*'),
        ),
        migrations.AddField(
            model_name='movie',
            name='name_2',
            field=models.CharField(blank=True, max_length=100, verbose_name='Название произведения*'),
        ),
        migrations.AddField(
            model_name='movie',
            name='participation',
            field=models.CharField(choices=[('1', 'очное'), ('2', 'заочное')], default='1', max_length=1, verbose_name='Тип участия*'),
        ),
        migrations.AddField(
            model_name='movie',
            name='poet_2',
            field=models.CharField(blank=True, max_length=100, verbose_name='Автор слов'),
        ),
        migrations.AddField(
            model_name='movie',
            name='youtube_flag_2',
            field=models.BooleanField(default=False, verbose_name='Признак YouTube'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profileuser.CoProfile', verbose_name='Исполнитель*'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='nomination',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nominations.VocalNomination', verbose_name='Номинация*'),
        ),
    ]
