# Generated by Django 2.2.24 on 2022-09-22 06:39

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('profileuser', '0007_remove_coprofile_rank'),
        ('movies', '0002_auto_20210927_0101'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoMovie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата регистрации')),
                ('coauthor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profileuser.CoProfile', verbose_name='Соисполнитель')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.Movie', verbose_name='Произведение')),
            ],
            options={
                'verbose_name': 'Соисполнитель',
                'verbose_name_plural': 'Соисполнители',
                'ordering': ['movie', 'coauthor'],
            },
        ),
    ]
