# Generated by Django 2.2.24 on 2023-09-18 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20230918_2342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='name_1',
            field=models.CharField(blank=True, max_length=100, verbose_name='Название первого произведения*'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='name_2',
            field=models.CharField(blank=True, max_length=100, verbose_name='Название второго произведения*'),
        ),
    ]
