# Generated by Django 2.2.24 on 2022-10-14 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_comovie'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='scene_num',
            field=models.DecimalField(blank=True, decimal_places=0, default=None, max_digits=3, null=True, verbose_name='Порядковый номер выступления'),
        ),
    ]
