# Generated by Django 2.2.24 on 2023-09-21 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_auto_20230921_2305'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='age',
            field=models.CharField(blank=True, max_length=30, verbose_name='Дата рождения исполнителя*'),
        ),
    ]
