# Generated by Django 2.2.24 on 2023-10-02 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_movie_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='descritpion',
            field=models.CharField(blank=True, max_length=250, verbose_name='Технические требования'),
        ),
    ]
