# Generated by Django 2.2.24 on 2023-10-14 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_movie_has_come'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='place',
            field=models.DecimalField(blank=True, decimal_places=0, default=None, max_digits=1, null=True, verbose_name='Место'),
        ),
    ]
