# Generated by Django 2.2.24 on 2025-09-07 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0009_auto_20240919_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='participation',
            field=models.CharField(choices=[('1', 'очное'), ('2', 'заочное')], default='1', max_length=1, verbose_name='Тип участия*'),
        ),
    ]
