# Generated by Django 2.2.24 on 2025-09-08 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0010_auto_20250907_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='participation',
            field=models.CharField(choices=[('1', 'очное'), ('2', 'онлайн-трансляция')], default='1', max_length=1, verbose_name='Тип участия*'),
        ),
    ]
