# Generated by Django 2.2.24 on 2025-10-13 07:47

from django.db import migrations, models
import movies.models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0011_auto_20250908_1316'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='certificate_file',
            field=models.FileField(blank=True, null=True, upload_to=movies.models.make_certificate_path, verbose_name='Сертификат'),
        ),
    ]
