# Generated by Django 2.2.24 on 2025-10-13 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0012_movie_certificate_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='certificate_file',
        ),
    ]
