# Generated by Django 2.2.24 on 2023-09-18 06:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=30, verbose_name='Username:')),
                ('category', models.CharField(choices=[('1', 'Студенты (профи) высших учебных заведений'), ('2', 'Студенты (любители) высших учебных заведений'), ('3', 'Студенты (профи) учреждений среднего профессионального образовани'), ('4', 'Студенты (любители) учреждений среднего профессионального образовани'), ('5', 'Профи'), ('6', 'Любители')], default='1', max_length=1, verbose_name='Категория участника')),
                ('surname', models.CharField(blank=True, max_length=50, verbose_name='Фамилия')),
                ('name', models.CharField(blank=True, max_length=30, verbose_name='Имя')),
                ('name2', models.CharField(blank=True, max_length=30, verbose_name='Отчество')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Телефон')),
                ('rank', models.TextField(blank=True, verbose_name='Звания')),
                ('profile_type', models.CharField(choices=[('0', 'участник'), ('1', 'руководитель'), ('2', 'преподаватель'), ('3', 'хормейстер'), ('4', 'концертмейстер'), ('5', 'хореограф')], default='0', max_length=1, verbose_name='Должность')),
                ('institution', models.CharField(blank=True, max_length=250, verbose_name='Полное назавние учреждения (в соответсие с ЕГЮРЛ)')),
                ('institution_shot', models.CharField(blank=True, max_length=250, verbose_name='Сокращеное назавние учреждения')),
                ('adress', models.CharField(blank=True, max_length=250, verbose_name='Адрес учреждения')),
                ('less_institution', models.BooleanField(default=False, verbose_name='Без учреждения')),
                ('member_access', models.BooleanField(default=True, verbose_name='Права участника')),
                ('admin_access', models.BooleanField(default=False, verbose_name='Права администратора')),
                ('message_accecc', models.BooleanField(default=False, verbose_name='Права рассылки оповещений')),
                ('juri_accecc', models.BooleanField(default=False, verbose_name='Член жюри')),
                ('chef_juri_accecc', models.BooleanField(default=False, verbose_name='Председатель жюри')),
                ('juri_type', models.CharField(choices=[('1', 'Вокал'), ('2', 'ДПИ')], default='1', max_length=1, verbose_name='Тип судейства')),
                ('has_come', models.BooleanField(default=False, verbose_name='Факт прибытия')),
                ('registration_date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата регистрации')),
                ('user', models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CoProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('self_flag', models.BooleanField(default=False, verbose_name='Признак себя')),
                ('profile_type', models.CharField(choices=[('0', 'участник'), ('1', 'руководитель'), ('2', 'преподаватель'), ('3', 'хормейстер'), ('4', 'концертмейстер'), ('5', 'хореограф')], default='0', max_length=1, verbose_name='Должность')),
                ('coprofile_type', models.CharField(choices=[('1', 'участник'), ('2', 'коллектив')], default='1', max_length=1, verbose_name='участник/коллектив')),
                ('surname', models.CharField(blank=True, max_length=50, verbose_name='Фамилия')),
                ('name', models.CharField(blank=True, max_length=30, verbose_name='Имя')),
                ('name2', models.CharField(blank=True, max_length=30, verbose_name='Отчество')),
                ('team', models.CharField(blank=True, max_length=30, verbose_name='Название коллектива')),
                ('registration_date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата регистрации')),
                ('main_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
