# Generated by Django 2.2.17 on 2021-01-04 08:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import profileuser.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=30, verbose_name='Username:')),
                ('surname', models.CharField(blank=True, max_length=50, verbose_name='Фамилия')),
                ('name', models.CharField(blank=True, max_length=30, verbose_name='Имя')),
                ('name2', models.CharField(blank=True, max_length=30, verbose_name='Отчество')),
                ('rank', models.TextField(blank=True, verbose_name='Звания')),
                ('institution', models.CharField(blank=True, max_length=250, verbose_name='Учреждение')),
                ('adress', models.CharField(blank=True, max_length=250, verbose_name='Адрес учреждения')),
                ('surname_director', models.CharField(blank=True, max_length=50, verbose_name='Фамилия руководителя учреждения')),
                ('name_director', models.CharField(blank=True, max_length=30, verbose_name='Имя руководителя учреждения')),
                ('name_director2', models.CharField(blank=True, max_length=30, verbose_name='Отчество руководителя учреждения')),
                ('certificate_num', models.CharField(blank=True, max_length=30, verbose_name='Номер сертификата')),
                ('certificate_file', models.FileField(blank=True, null=True, upload_to=profileuser.models.make_certificate_path, verbose_name='Сертификат')),
                ('registration_date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата регистрации')),
                ('member_access', models.BooleanField(default=True, verbose_name='Права участника')),
                ('admin_access', models.BooleanField(default=False, verbose_name='Права администратора')),
                ('moderator_access', models.BooleanField(default=False, verbose_name='Права модератора')),
                ('message_accecc', models.BooleanField(default=False, verbose_name='Права рассылки оповещений')),
                ('juri_accecc', models.BooleanField(default=False, verbose_name='Член жюри')),
                ('chef_juri_accecc', models.BooleanField(default=False, verbose_name='Председатель жюри')),
                ('user', models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
