# Generated by Django 2.2.24 on 2023-09-18 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileuser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coprofile',
            name='name',
            field=models.CharField(blank=True, max_length=30, verbose_name='Имя*'),
        ),
        migrations.AlterField(
            model_name='coprofile',
            name='profile_type',
            field=models.CharField(choices=[('0', 'участник'), ('1', 'руководитель'), ('2', 'преподаватель'), ('3', 'хормейстер'), ('4', 'концертмейстер'), ('5', 'хореограф')], default='0', max_length=1, verbose_name='Должность*'),
        ),
        migrations.AlterField(
            model_name='coprofile',
            name='surname',
            field=models.CharField(blank=True, max_length=50, verbose_name='Фамилия*'),
        ),
        migrations.AlterField(
            model_name='coprofile',
            name='team',
            field=models.CharField(blank=True, max_length=30, verbose_name='Название коллектива*'),
        ),
    ]
