# Generated by Django 2.2.24 on 2023-10-09 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileuser', '0002_auto_20230918_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coprofile',
            name='team',
            field=models.CharField(blank=True, max_length=511, verbose_name='Название коллектива*'),
        ),
    ]
