# Generated by Django 2.2.24 on 2022-09-21 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileuser', '0002_profile_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='participation',
            field=models.CharField(choices=[('1', 'Очное'), ('2', 'Заочное')], default='1', max_length=1, verbose_name='Тип участия'),
        ),
    ]
