# Generated by Django 2.2.24 on 2023-10-11 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileuser', '0003_auto_20231009_1901'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='register_accecc',
            field=models.BooleanField(default=False, verbose_name='Права встречающего'),
        ),
    ]
