# Generated by Django 2.2.24 on 2023-10-11 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profileuser', '0004_profile_register_accecc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='has_come',
        ),
    ]
