# Generated by Django 2.2.24 on 2022-09-21 19:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import profileuser.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profileuser', '0004_auto_20220921_2142'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_type', models.CharField(choices=[('1', 'Руководитель'), ('2', 'Преподаватель'), ('3', 'Концертмейстер'), ('4', 'Хореограф')], default='1', max_length=1, verbose_name='Категория')),
                ('surname', models.CharField(blank=True, max_length=50, verbose_name='Фамилия')),
                ('name', models.CharField(blank=True, max_length=30, verbose_name='Имя')),
                ('name2', models.CharField(blank=True, max_length=30, verbose_name='Отчество')),
                ('rank', models.TextField(blank=True, verbose_name='Звания')),
                ('certificate_num', models.CharField(blank=True, max_length=30, verbose_name='Номер сертификата')),
                ('certificate_file', models.FileField(blank=True, null=True, upload_to=profileuser.models.make_certificate_path, verbose_name='Сертификат')),
                ('registration_date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата регистрации')),
                ('main_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
