# Generated by Django 2.2.24 on 2022-09-21 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileuser', '0005_coprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coprofile',
            name='profile_type',
            field=models.CharField(choices=[('1', 'Руководитель'), ('2', 'Преподаватель'), ('3', 'Хормейстер'), ('4', 'Концертмейстер'), ('5', 'Хореограф')], default='1', max_length=1, verbose_name='Категория'),
        ),
    ]
