# Generated by Django 2.2.24 on 2025-10-13 08:29

from django.db import migrations, models
import profileuser.models


class Migration(migrations.Migration):

    dependencies = [
        ('profileuser', '0005_remove_profile_has_come'),
    ]

    operations = [
        migrations.AddField(
            model_name='coprofile',
            name='certificate_file',
            field=models.FileField(blank=True, null=True, upload_to=profileuser.models.make_certificate_path, verbose_name='Сертификат'),
        ),
    ]
