# Generated by Django 2.2.24 on 2022-09-21 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profileuser', '0006_auto_20220921_2301'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coprofile',
            name='rank',
        ),
    ]
