# Generated by Django 2.2.24 on 2022-09-22 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileuser', '0007_remove_coprofile_rank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coprofile',
            name='profile_type',
            field=models.CharField(choices=[('1', 'руководитель'), ('2', 'преподаватель'), ('3', 'хормейстер'), ('4', 'концертмейстер'), ('5', 'хореограф')], default='1', max_length=1, verbose_name='Категория'),
        ),
    ]
