# Generated by Django 2.2.24 on 2022-10-08 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileuser', '0008_auto_20220922_1646'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, max_length=30, verbose_name='Телефон'),
        ),
    ]
