# Generated by Django 2.2.24 on 2022-10-14 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileuser', '0009_profile_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='juri_type',
            field=models.CharField(choices=[('1', 'Вокал'), ('2', 'ДПИ')], default='1', max_length=1, verbose_name='Тип судейства'),
        ),
    ]
