# Generated by Django 2.2.24 on 2022-10-14 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileuser', '0010_profile_juri_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='has_come',
            field=models.BooleanField(default=False, verbose_name='Факт прибытия'),
        ),
        migrations.AddField(
            model_name='profile',
            name='order_block',
            field=models.BooleanField(default=False, verbose_name='Запрет расстановки номеров'),
        ),
    ]
